# Generated by Django 4.0.3 on 2022-03-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_doctor_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='doctors',
            field=models.ManyToManyField(blank=True, null=True, related_name='doctors', to='account.doctor'),
        ),
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
