# Generated by Django 4.0.3 on 2022-03-13 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
