# Generated by Django 4.0.3 on 2022-03-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_symptom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptom',
            name='status',
        ),
        migrations.AddField(
            model_name='submission',
            name='verdict',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
