# Generated by Django 4.0.3 on 2022-03-12 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_remove_symptom_status_submission_verdict'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('submisson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to='health.submission')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_symptons', to='health.symptom')),
            ],
        ),
    ]
