# Generated by Django 4.0.3 on 2022-03-13 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_alter_submission_verdict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
